# Oscar first POD
apiVersion: v1
kind: Pod
metadata:
  name: oscar-pod
  labels:
    app:  webserver
  annotations:
    tag:  v0.0.1  
    author: Oscar Wei
    author_email: oscarwei168@msn.com
    release_date: 2019/05/10
spec:
  restartPolicy: OnFailure
  volumes:
    - name: "oscar-volume"
      hostPath:
        path: "/Users/oscarwei168/Documents/Oscar/Projects/k8s/volumes"
    - name: secret-volume # volume for host machine
      secret:
        secretName: oscar-secret    
  # nodeSelector:
  #   env: qa      
  containers:
    - name: nginx-oscar
      image: oscarwei168/nginx-oscar:alpine
      imagePullPolicy: IfNotPresent # by default, can change to 'Always/Never' for imagePullSecrets
      ports:
        - containerPort: 80 # for container port
          name: http
          protocol: TCP # TCP by default or otherwire UDP
          # hostIP: 0.0.0.0
          # hostPort: 80 # for host port
      # command:
      #   - echo
      #   - "Hello World"
      volumeMounts:
        - name: secret-volume # volume for container
          mountPath: /etc/creds
          readOnly: true    
      resources:
        requests:
          memory: "64Mi" # 64M memory
          cpu:  "250m" # 0.25 cpu core
        limits:
          memory: "128Mi" # 128M memory
          cpu:  "1000m" # 1 cpu core
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      env:
      - name: SECRET_NAME
        valueFrom:
          secretKeyRef:
            name: oscar-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: oscar-secret
            key: password
      - name: OSCAR_DEPLOYMENT_SERVICE
        value: oscar-deployment-service # use kube-dns to bind service  
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP              
  # imagePullSecrets:
  #   - oscar-registry-key          

