# Oscar Replication Controller
apiVersion: v1
kind: ReplicationController
metadata:
  name: oscar-replication-controller
spec:
  replicas: 3
  selector: # the labels for the Pods that this Replication Controller should monitor
    app:  oscar-pod-v1
  template:
    metadata:
      labels:
        app:  oscar-pod-v1
    spec:
      containers:
        - name: oscar-pod
          image: oscarwei168/nginx-oscar:alpine
          ports:
            - containerPort: 80
  