# Oscar first POD
apiVersion: v1
kind: Pod
metadata:
  name: oscar-pod
  labels:
    app:  webserver
spec:
  volumes:
    - name: "oscar-volume"
      hostPath:
        path: "/Users/oscarwei168/Documents/Oscar/Projects/k8s/pods/volumes"
  containers:
    - name: oscar-pod
      image: oscarwei168/oscar-docker
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      resources:
        requests:
          memory: "64Mi" # 64M memory
          cpu:  "250m" # 0.25 cpu core
        limits:
          memory: "128Mi" # 128M memory
          cpu:  "1000m" # 1 cpu core
      livenessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 5
        timeoutSeconds: 10
        periodSeconds: 10
        failureThreshold: 3